<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Job Seekers</name>
   <tag></tag>
   <elementGuidId>637d618e-be25-4755-88b2-6105bfa0daaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//c-sidebar[@id='sidebar']/perfect-scrollbar/div/div/c-sidebar-nav/c-sidebar-nav-link[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2212788c-4e58-4318-8315-3fc6de8aabaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>9b6e5aaf-fe6f-4ca9-ba02-7675a6698dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-star-inserted</value>
      <webElementGuid>f9033a14-5b88-4f45-b820-4203ffa5c639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-seekers</value>
      <webElementGuid>5032f743-c900-406f-8793-d024fb4a4398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Seekers</value>
      <webElementGuid>48a2197c-7c3d-4d83-9ac5-5cbdd372dd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/perfect-scrollbar[1]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/c-sidebar-nav[@class=&quot;sidebar-nav&quot;]/c-sidebar-nav-link[@class=&quot;nav-item ng-star-inserted&quot;]/a[@class=&quot;nav-link ng-star-inserted&quot;]</value>
      <webElementGuid>d202520f-790c-4cb5-91c0-8eae2545e33f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//c-sidebar[@id='sidebar']/perfect-scrollbar/div/div/c-sidebar-nav/c-sidebar-nav-link[7]/a</value>
      <webElementGuid>c3cb3dbf-6646-4bbd-8498-1ce67de77f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/following::a[1]</value>
      <webElementGuid>ac375221-17b1-4ffc-af2d-cc8b8800ef50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experience'])[1]/following::a[2]</value>
      <webElementGuid>68791d9b-20f8-4459-a5a1-5ad807b6157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Templates'])[1]/preceding::a[1]</value>
      <webElementGuid>0a0c1bac-8e48-4056-b114-16802fe424eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job-seekers')]</value>
      <webElementGuid>dce7f6a1-766e-4105-b9c9-b53e88c66921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-sidebar-nav-link[7]/a</value>
      <webElementGuid>aaf854cb-9ff4-434b-bde0-965623627428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-seekers' and (text() = 'Job Seekers' or . = 'Job Seekers')]</value>
      <webElementGuid>bc6002c3-6439-419e-8a7b-8b766f5b7bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
