<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Users_Add</name>
   <tag></tag>
   <elementGuidId>f47108d1-2a9e-467d-92f3-e663d8cb9468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;users&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='users']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e4bda10-5577-4cbf-a401-d35401b867fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f8c8868-b56b-4517-8d97-1ab35eabbdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-group oneChecked_add_0 ng-star-inserted</value>
      <webElementGuid>efab0f5b-61f4-45db-8549-a1632e36d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>1fca8ac0-86f0-48e8-8ebf-48bb442fc2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>users</value>
      <webElementGuid>f9e6fba5-b359-421c-9801-2b5e33211c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed page-quick-sidebar-over-content&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper d-flex flex-column&quot;]/div[@class=&quot;body flex-grow-1&quot;]/c-container[@class=&quot;h-auto container-lg&quot;]/app-user-group-add[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;portlet box blue-steel float-none content-box my-md-4 mx-md-3 border-0&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;portlet-body form bg-transparent p-3 border-0&quot;]/div[@class=&quot;p-3&quot;]/c-row[@class=&quot;mb-3 row&quot;]/c-col[@class=&quot;col-sm-6&quot;]/table[@class=&quot;checkbox-table&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/p[1]/input[@class=&quot;checkbox-group oneChecked_add_0 ng-star-inserted&quot;]</value>
      <webElementGuid>53ee615f-b2ea-4ce2-8857-ec6506900d08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='users']</value>
      <webElementGuid>17345eee-6767-4240-aee8-652e430f9b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>ad3c341d-7efa-4bd2-ab82-e2a110636799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'users']</value>
      <webElementGuid>4c1f28e3-c095-4a1d-a8d4-4953279c9c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
