<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>0829b4ca-59d6-492d-a67e-412831052590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.bg-success.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db0520b0-d534-4b2c-8cf2-889f7d053cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa43478c-033e-4a05-b427-75692251c3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn bg-success text-white</value>
      <webElementGuid>ca255381-1362-4445-9c9a-a541232a3e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>bafdbd1c-927a-474c-8f96-a3b469e19bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed page-quick-sidebar-over-content&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper d-flex flex-column&quot;]/div[@class=&quot;body flex-grow-1&quot;]/c-container[@class=&quot;h-auto container-lg&quot;]/app-email-template[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;portlet box yellow-crusta float-none content-box my-md-4 mx-md-3 border-0&quot;]/div[@class=&quot;portlet-body form bg-transparent p-3 border-0&quot;]/div[@class=&quot;table-responsive table-scrollable border-0&quot;]/table[@class=&quot;table table-customize&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[5]/button[@class=&quot;btn bg-success text-white&quot;]</value>
      <webElementGuid>1751f29e-846c-4c87-aef3-8010108345f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>fe4ba044-2b61-429d-95cd-498c3227222d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/following::button[1]</value>
      <webElementGuid>b35173d5-e133-4e28-874a-e81fd61e799e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test-webs'])[1]/following::button[1]</value>
      <webElementGuid>b98c75d3-48eb-4da0-8f80-0b0f39c41cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website Test'])[1]/preceding::button[1]</value>
      <webElementGuid>b913905f-3dea-48c9-9459-4a02a8d3b070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='web-test'])[1]/preceding::button[1]</value>
      <webElementGuid>4e80bb13-9579-466e-9239-dff9d3787955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>54799abf-e30c-4f71-b9a3-d082d0f04034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button</value>
      <webElementGuid>d6f8c453-7c8b-4062-8b29-05bd56f6f529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>6404ff1f-c1db-4c35-974a-6b42c4805c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
