<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>546fc665-004d-4b71-82b8-f2d722ca2be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-untouched.ng-pristine.ng-invalid.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a95a4781-fec2-429e-8717-b052c2994c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95e862e8-1fc0-424a-b42a-51c364b66f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>877e91fa-088e-41fd-955c-409a5f5e196a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid form-control</value>
      <webElementGuid>8301f90a-650a-416c-9466-c3d9609d8532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed page-quick-sidebar-over-content&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper d-flex flex-column&quot;]/div[@class=&quot;body flex-grow-1&quot;]/c-container[@class=&quot;h-auto container-lg&quot;]/app-menu-add[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;portlet box blue-steel float-none content-box my-md-4 mx-md-3 border-0&quot;]/div[@class=&quot;portlet-body form bg-transparent p-3 border-0&quot;]/form[@class=&quot;form-horizontal ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;p-3&quot;]/c-row[@class=&quot;mb-3 row&quot;]/c-col[@class=&quot;col-sm-4&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-invalid form-control&quot;]</value>
      <webElementGuid>d58dea42-2401-407e-9153-945d23c465d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>98f74ade-d9fe-40a7-8697-dc3d7a123205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>67494768-49bb-4412-8799-96c61872783a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>70d44c09-692f-4198-a310-80c0defe0b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
